### ISSUE TITLE
Nirvana es mi banda favorita.

### ISSUE THREAD

**Issue by gottaeat** [gottaeat/bands#5]
```python
:lol!~lmao@haha.poop PRIVMSG #linux :Recuerdo cuando escuché por primera vez esta canción,
Traceback (most recent call last):
  File "/home/mss/.pyenv/versions/fuckaround/bin/bands", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/mss/.pyenv/versions/3.11.5/envs/fuckaround/lib/python3.11/site-packages/bands/cli.py", line 47, in run
    c.run()
  File "/home/mss/.pyenv/versions/3.11.5/envs/fuckaround/lib/python3.11/site-packages/bands/cli.py", line 41, in run
    irc.run()
  File "/home/mss/.pyenv/versions/3.11.5/envs/fuckaround/lib/python3.11/site-packages/bands/irc.py", line 19, in run
    data = strip_color(self.core.conn.recv(2048).decode(encoding="UTF-8"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 66: invalid continuation byte
```

**Comment by gottaeat** [comment]
a0bf2e67f8ce58991eb2ce2bdce017a5f45b52d5 fixes this.
